use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;

use serde::{Deserialize, Serialize};

use crate::api::provider::LlmProvider;
use crate::api::types::{ChatMessage, MessageRole};
use crate::error::{AgentError, Result};
use crate::infra::graph::{
    Dependency, DependencyType, DiscoveryMethod, InfraGraph, Service, ServiceType,
};
use crate::tools::shell::ShellTool;
use crate::tools::target::TargetHost;
use crate::tools::traits::{Tool, ToolParams};

// ─── Phase 1: Fingerprint probes (hardcoded, fast, no LLM) ───

const FINGERPRINT_PROBES: &[(&str, &str)] = &[
    ("os_release", "cat /etc/os-release"),
    ("uname", "uname -a"),
    ("listening_ports", "ss -tlnp"),
    ("processes", "ps auxf --no-headers"),
    ("systemd_services", "systemctl list-units --type=service --state=running --no-pager --no-legend"),
];

const RUNTIME_PROBES: &[(&str, &str)] = &[
    ("docker", "docker version --format json"),
    ("podman", "podman version --format json"),
    ("kubectl", "kubectl version --client --output json"),
    ("docker_compose", "docker compose version"),
    ("nginx", "nginx -v"),
    ("haproxy", "haproxy -v"),
    ("apache", "apache2 -v"),
    ("httpd", "httpd -v"),
    ("caddy", "caddy version"),
    ("traefik", "traefik version"),
];

// ─── Types ───

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerFingerprint {
    pub os: String,
    pub arch: String,
    pub init_system: String,
    pub runtimes: Vec<String>,
    pub orchestrators: Vec<String>,
    pub web_servers: Vec<String>,
    pub listening_ports: Vec<(u16, String)>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiscoveryCommand {
    pub cmd: String,
    pub purpose: String,
    #[serde(default)]
    pub needs_sudo: bool,
}

#[derive(Debug, Clone)]
pub enum CommandResult {
    Success { cmd: String, output: String },
    PermissionDenied { cmd: String, error: String },
    NotFound { cmd: String },
    Timeout { cmd: String },
    OtherError { cmd: String, error: String },
}

impl CommandResult {
    pub fn is_permission_denied(&self) -> bool {
        matches!(self, Self::PermissionDenied { .. })
    }

    pub fn cmd(&self) -> &str {
        match self {
            Self::Success { cmd, .. }
            | Self::PermissionDenied { cmd, .. }
            | Self::NotFound { cmd }
            | Self::Timeout { cmd }
            | Self::OtherError { cmd, .. } => cmd,
        }
    }
}

// ─── Discovery Agent ───

pub struct DiscoveryAgent {
    client: Arc<dyn LlmProvider>,
}

impl DiscoveryAgent {
    pub fn new(client: Arc<dyn LlmProvider>) -> Self {
        Self { client }
    }

    /// Full adaptive discovery pipeline.
    pub async fn discover(&self, target: &TargetHost, use_sudo: bool) -> Result<InfraGraph> {
        let shell = ShellTool::new(target.clone());

        // Phase 1: Fingerprint
        tracing::info!("Phase 1: Fingerprinting server...");
        let (fingerprint, baseline_data) = self.fingerprint(&shell).await?;
        tracing::info!(
            os = %fingerprint.os,
            runtimes = ?fingerprint.runtimes,
            web_servers = ?fingerprint.web_servers,
            ports = fingerprint.listening_ports.len(),
            "Server fingerprinted"
        );

        // Phase 2: LLM generates tailored commands
        tracing::info!("Phase 2: Generating discovery commands...");
        let commands = self.generate_commands(&fingerprint).await?;
        tracing::info!(commands = commands.len(), "Commands generated by LLM");

        // Phase 3: Execute commands with failure classification
        tracing::info!("Phase 3: Executing {} discovery commands...", commands.len());
        let (results, denied) = self.execute_commands(&shell, &commands, false).await;
        let success_count = results.iter().filter(|r| matches!(r, CommandResult::Success { .. })).count();
        let denied_count = denied.len();
        tracing::info!(success = success_count, denied = denied_count, "Commands executed");

        // Phase 3b: Retry denied commands with sudo if --sudo flag set
        let mut sudo_results = Vec::new();
        if use_sudo && !denied.is_empty() {
            tracing::info!(retrying = denied.len(), "Retrying with sudo...");
            let sudo_cmds: Vec<DiscoveryCommand> = denied
                .iter()
                .map(|r| DiscoveryCommand {
                    cmd: format!("sudo {}", r.cmd()),
                    purpose: "Retry with elevated privileges".into(),
                    needs_sudo: true,
                })
                .collect();
            let (sudo_res, still_denied) = self.execute_commands(&shell, &sudo_cmds, true).await;
            let sudo_success = sudo_res.iter().filter(|r| matches!(r, CommandResult::Success { .. })).count();
            tracing::info!(
                succeeded = sudo_success,
                still_denied = still_denied.len(),
                "Sudo retry complete"
            );
            sudo_results = sudo_res;
        } else if !denied.is_empty() {
            eprintln!(
                "\n⚠ Partial discovery: {} commands skipped (permission denied)",
                denied_count
            );
            eprintln!("  Run `opcrew infra discover --sudo` for full access\n");
        }

        // Phase 4: Collect all successful output
        let mut all_data: Vec<(String, String)> = baseline_data;
        for result in results.iter().chain(sudo_results.iter()) {
            if let CommandResult::Success { cmd, output } = result {
                all_data.push((cmd.clone(), output.clone()));
            }
        }

        // Phase 5: LLM extracts graph
        tracing::info!("Phase 4: Extracting infrastructure graph...");
        let mut graph = self.extract_graph(&all_data).await?;

        // Post-process: resolve unknowns from raw ss data
        let unknown_count = graph.services.keys().filter(|k| k.starts_with("unknown") || k.starts_with("custom")).count();
        if unknown_count > 0 {
            resolve_unknown_services(&mut graph, &all_data);
        }

        // Add gaps for denied commands
        if !use_sudo && denied_count > 0 {
            graph.gaps.push(format!(
                "{denied_count} commands skipped (permission denied). Use --sudo for full discovery."
            ));
        }

        tracing::info!(
            services = graph.services.len(),
            dependencies = graph.dependencies.len(),
            gaps = graph.gaps.len(),
            "Discovery complete"
        );

        Ok(graph)
    }

    /// Phase 1: Fingerprint — detect OS, runtimes, orchestrators, web servers.
    async fn fingerprint(&self, shell: &ShellTool) -> Result<(ServerFingerprint, Vec<(String, String)>)> {
        let mut baseline_data = Vec::new();
        let mut os = String::from("Linux");
        let mut arch = String::new();

        // Run baseline probes
        for (name, cmd) in FINGERPRINT_PROBES {
            if let Some(output) = run_cmd(shell, cmd).await {
                if *name == "os_release" {
                    for line in output.lines() {
                        if let Some(pretty) = line.strip_prefix("PRETTY_NAME=") {
                            os = pretty.trim_matches('"').to_string();
                        }
                    }
                }
                if *name == "uname" {
                    arch = output.split_whitespace().nth(4).unwrap_or("").to_string();
                }
                baseline_data.push((name.to_string(), output));
            }
        }

        // Parse listening ports from ss output
        let listening_ports: Vec<(u16, String)> = baseline_data
            .iter()
            .filter(|(name, _)| name == "listening_ports")
            .flat_map(|(_, output)| {
                output.lines().filter_map(|line| {
                    let port = extract_port_from_ss(line)?;
                    let program = extract_program_from_ss(line).unwrap_or_default();
                    Some((port, program))
                })
            })
            .collect();

        // Detect runtimes/orchestrators/web servers
        let mut runtimes = Vec::new();
        let mut orchestrators = Vec::new();
        let mut web_servers = Vec::new();

        for (name, cmd) in RUNTIME_PROBES {
            if let Some(output) = run_cmd(shell, cmd).await {
                baseline_data.push((format!("probe_{name}"), output));
                match *name {
                    "docker" | "podman" => runtimes.push(name.to_string()),
                    "kubectl" => orchestrators.push("kubernetes".to_string()),
                    "docker_compose" => orchestrators.push("docker-compose".to_string()),
                    "nginx" | "haproxy" | "apache" | "httpd" | "caddy" | "traefik" => {
                        web_servers.push(name.to_string());
                    }
                    _ => {}
                }
            }
        }

        let fingerprint = ServerFingerprint {
            os,
            arch,
            init_system: "systemd".into(), // assume systemd if systemctl worked
            runtimes,
            orchestrators,
            web_servers,
            listening_ports,
        };

        Ok((fingerprint, baseline_data))
    }

    /// Phase 2: LLM generates tailored discovery commands.
    async fn generate_commands(&self, fingerprint: &ServerFingerprint) -> Result<Vec<DiscoveryCommand>> {
        let fp_json = serde_json::to_string_pretty(fingerprint)
            .map_err(|e| AgentError::InfraError(format!("Serialize fingerprint: {e}")))?;

        let prompt = format!(
            "Server fingerprint:\n```json\n{fp_json}\n```\n\n\
             Generate read-only discovery commands for this server.\n\
             Return ONLY a JSON array: [{{\"cmd\": \"...\", \"purpose\": \"...\", \"needs_sudo\": false}}]"
        );

        let messages = vec![ChatMessage {
            role: MessageRole::User,
            content: prompt,
        }];

        // Try up to 3 times — LLMs sometimes produce malformed JSON
        let mut last_response = String::new();
        let mut conversation = messages;

        for attempt in 0..3 {
            let (response, _) = self
                .client
                .send_message(COMMAND_GEN_SYSTEM_PROMPT, &conversation)
                .await?;

            let json_str = crate::api::schema::extract_json(&response);
            match serde_json::from_str::<Vec<DiscoveryCommand>>(&json_str) {
                Ok(commands) => return Ok(commands.into_iter().take(30).collect()),
                Err(e) => {
                    tracing::warn!(attempt, error = %e, "LLM returned invalid command JSON, retrying");
                    last_response = response;
                    // Add feedback for retry
                    conversation.push(ChatMessage {
                        role: MessageRole::Assistant,
                        content: last_response.clone(),
                    });
                    conversation.push(ChatMessage {
                        role: MessageRole::User,
                        content: format!(
                            "Your JSON is invalid: {e}. Fix it and return ONLY a valid JSON array."
                        ),
                    });
                }
            }
        }

        Err(AgentError::InfraError(format!(
            "Failed to get valid command list after 3 attempts. Last response: {}",
            &last_response[..last_response.len().min(200)]
        )))
    }

    /// Phase 3: Execute commands with failure classification.
    async fn execute_commands(
        &self,
        shell: &ShellTool,
        commands: &[DiscoveryCommand],
        is_sudo_retry: bool,
    ) -> (Vec<CommandResult>, Vec<CommandResult>) {
        let mut results = Vec::new();
        let mut denied = Vec::new();

        for cmd_spec in commands {
            let cmd = &cmd_spec.cmd;

            // Skip shell composition (safety)
            if ShellTool::has_composition(cmd) {
                tracing::warn!(cmd = %cmd, "Skipping: shell composition detected");
                continue;
            }

            let params = ToolParams {
                tool_name: "shell".into(),
                action: "run".into(),
                args: [("command".into(), cmd.clone())].into(),
            };

            match shell.execute(&params, Duration::from_secs(30)).await {
                Ok(result) if result.success => {
                    results.push(CommandResult::Success {
                        cmd: cmd.clone(),
                        output: result.output,
                    });
                }
                Ok(result) => {
                    let error = result.error.unwrap_or_default();
                    let combined = format!("{}{}", result.output, error);
                    if combined.contains("Permission denied")
                        || combined.contains("permission denied")
                        || combined.contains("Operation not permitted")
                        || combined.contains("Access denied")
                    {
                        let cr = CommandResult::PermissionDenied {
                            cmd: cmd.clone(),
                            error: combined,
                        };
                        if !is_sudo_retry {
                            denied.push(cr);
                        } else {
                            results.push(cr);
                        }
                    } else if combined.contains("not found") || combined.contains("No such file") {
                        results.push(CommandResult::NotFound { cmd: cmd.clone() });
                    } else {
                        // Non-fatal error — still include partial output if any
                        if !result.output.is_empty() {
                            results.push(CommandResult::Success {
                                cmd: cmd.clone(),
                                output: result.output,
                            });
                        } else {
                            results.push(CommandResult::OtherError {
                                cmd: cmd.clone(),
                                error: combined,
                            });
                        }
                    }
                }
                Err(AgentError::ToolTimeout { .. }) => {
                    results.push(CommandResult::Timeout { cmd: cmd.clone() });
                }
                Err(_) => {
                    results.push(CommandResult::NotFound { cmd: cmd.clone() });
                }
            }
        }

        (results, denied)
    }

    /// Phase 5: LLM extracts infrastructure graph from all collected data.
    async fn extract_graph(&self, all_data: &[(String, String)]) -> Result<InfraGraph> {
        let mut prompt = String::from("Extract the infrastructure graph from this system output.\n\n");
        let mut total_len = 0;
        for (name, output) in all_data {
            let truncated = &output[..output.len().min(3000)];
            prompt.push_str(&format!("### {name}\n```\n{truncated}\n```\n\n"));
            total_len += truncated.len();
            if total_len > 40000 {
                prompt.push_str("(remaining output truncated for context limit)\n");
                break;
            }
        }
        prompt.push_str(
            "Return ONLY valid JSON:\n\
{\"services\": [{\"name\": \"svc\", \"host\": \"localhost\", \"port\": 80, \
\"service_type\": \"Web\", \"discovered_via\": \"Systemd\", \
\"log_paths\": [], \"config_paths\": [], \"process_name\": \"nginx\"}], \
\"dependencies\": [{\"from\": \"a\", \"to\": \"b\", \"dep_type\": \"Required\", \
\"discovered_via\": \"config\"}], \"hosts\": [\"localhost\"]}"
        );

        let messages = vec![ChatMessage {
            role: MessageRole::User,
            content: prompt,
        }];

        let (response, _) = self
            .client
            .send_message(EXTRACTION_SYSTEM_PROMPT, &messages)
            .await?;

        let json_str = crate::api::schema::extract_json(&response);
        let raw: serde_json::Value = serde_json::from_str(&json_str)
            .map_err(|e| AgentError::InfraError(format!("Invalid JSON from LLM: {e}")))?;

        parse_graph_flexible(&raw)
    }
}

// ─── Helper: run a command, return output or None ───

async fn run_cmd(shell: &ShellTool, cmd: &str) -> Option<String> {
    if ShellTool::has_composition(cmd) {
        return None;
    }
    let params = ToolParams {
        tool_name: "shell".into(),
        action: "run".into(),
        args: [("command".into(), cmd.to_string())].into(),
    };
    match shell.execute(&params, Duration::from_secs(15)).await {
        Ok(result) if result.success && !result.output.is_empty() => Some(result.output),
        _ => None,
    }
}

// ─── Graph parsing (flexible: array or object) ───

fn parse_graph_flexible(raw: &serde_json::Value) -> Result<InfraGraph> {
    let mut graph = InfraGraph::new();

    if let Some(services) = raw.get("services") {
        match services {
            serde_json::Value::Array(arr) => {
                for item in arr {
                    if let Some(svc) = parse_service_from_value(item) {
                        graph.services.insert(svc.name.clone(), svc);
                    }
                }
            }
            serde_json::Value::Object(map) => {
                for (name, item) in map {
                    if let Some(mut svc) = parse_service_from_value(item) {
                        if svc.name.is_empty() {
                            svc.name = name.clone();
                        }
                        graph.services.insert(svc.name.clone(), svc);
                    }
                }
            }
            _ => {}
        }
    }

    if let Some(serde_json::Value::Array(deps)) = raw.get("dependencies") {
        for item in deps {
            let from = item.get("from").and_then(|v| v.as_str()).unwrap_or_default().to_string();
            let to = item.get("to").and_then(|v| v.as_str()).unwrap_or_default().to_string();
            let dep_type_str = item.get("dep_type").and_then(|v| v.as_str()).unwrap_or("Required");
            let discovered_via = item.get("discovered_via").and_then(|v| v.as_str()).unwrap_or("").to_string();

            if !from.is_empty() && !to.is_empty() {
                graph.dependencies.push(Dependency {
                    from, to,
                    dep_type: match dep_type_str {
                        "Optional" => DependencyType::Optional,
                        "LoadBalanced" => DependencyType::LoadBalanced,
                        _ => DependencyType::Required,
                    },
                    discovered_via,
                });
            }
        }
    }

    if let Some(serde_json::Value::Array(hosts)) = raw.get("hosts") {
        graph.hosts = hosts.iter().filter_map(|v| v.as_str().map(String::from)).collect();
    }
    if graph.hosts.is_empty() {
        let hosts: std::collections::HashSet<String> = graph.services.values().map(|s| s.host.clone()).collect();
        graph.hosts = hosts.into_iter().collect();
    }

    Ok(graph)
}

fn parse_service_from_value(v: &serde_json::Value) -> Option<Service> {
    let name = v.get("name").or(v.get("service_name")).and_then(|n| n.as_str())?.to_string();
    let host = v.get("host").and_then(|h| h.as_str()).unwrap_or("localhost").to_string();
    let port = v.get("port").and_then(|p| p.as_u64()).map(|p| p as u16);
    let process_name = v.get("process_name").and_then(|p| p.as_str()).map(String::from);
    let log_paths: Vec<String> = match v.get("log_paths").or(v.get("log_path")) {
        Some(serde_json::Value::Array(arr)) => arr.iter().filter_map(|x| x.as_str().map(String::from)).collect(),
        Some(serde_json::Value::String(s)) if !s.is_empty() => vec![s.clone()],
        _ => vec![],
    };
    let config_paths: Vec<String> = match v.get("config_paths").or(v.get("config_path")) {
        Some(serde_json::Value::Array(arr)) => arr.iter().filter_map(|x| x.as_str().map(String::from)).collect(),
        Some(serde_json::Value::String(s)) if !s.is_empty() => vec![s.clone()],
        _ => vec![],
    };
    let health_check = v.get("health_check").and_then(|h| h.as_str()).map(String::from);
    let service_type = match v.get("service_type").and_then(|s| s.as_str()).unwrap_or("Custom") {
        "Web" => ServiceType::Web, "Database" => ServiceType::Database,
        "Cache" => ServiceType::Cache, "Queue" => ServiceType::Queue,
        "LoadBalancer" => ServiceType::LoadBalancer, _ => ServiceType::Custom,
    };
    let discovered_via = match v.get("discovered_via").and_then(|d| d.as_str()).unwrap_or("Process") {
        "Systemd" => DiscoveryMethod::Systemd, "Port" => DiscoveryMethod::Port,
        "Docker" => DiscoveryMethod::Docker, "Manual" => DiscoveryMethod::Manual,
        _ => DiscoveryMethod::Process,
    };

    // Infer execution context from discovery method and name
    let execution_context = match discovered_via {
        DiscoveryMethod::Docker => crate::infra::graph::ExecutionContext::docker(&name),
        DiscoveryMethod::Systemd => crate::infra::graph::ExecutionContext {
            runtime: "systemd".into(), identifier: name.clone(), extra: Default::default(),
        },
        _ => crate::infra::graph::ExecutionContext::local(),
    };

    Some(Service { name, host, port, process_name, log_paths, config_paths, health_check, service_type, discovered_via, execution_context })
}

// ─── Post-processing: resolve unknowns from raw ss/docker data ───

fn resolve_unknown_services(graph: &mut InfraGraph, raw_data: &[(String, String)]) {
    let mut port_to_program: HashMap<u16, String> = HashMap::new();
    let mut port_to_container: HashMap<u16, String> = HashMap::new();

    for (name, output) in raw_data {
        if name == "listening_ports" || name.contains("ss") {
            for line in output.lines() {
                if let (Some(port), Some(program)) = (extract_port_from_ss(line), extract_program_from_ss(line)) {
                    port_to_program.insert(port, program);
                }
            }
        }
        // Parse docker ps output (various formats)
        if name.contains("docker") && output.contains("Names") {
            for line in output.lines() {
                if let Ok(v) = serde_json::from_str::<serde_json::Value>(line) {
                    let container_name = v.get("Names").and_then(|n| n.as_str()).unwrap_or_default();
                    let ports = v.get("Ports").and_then(|p| p.as_str()).unwrap_or_default();
                    for mapping in ports.split(", ") {
                        if let Some(host_port) = mapping.split("->").next()
                            .and_then(|s| s.rsplit(':').next())
                            .and_then(|p| p.parse::<u16>().ok())
                            .filter(|_| !container_name.is_empty())
                        {
                            port_to_container.insert(host_port, container_name.to_string());
                        }
                    }
                }
            }
        }
    }

    let keys_to_fix: Vec<String> = graph.services.keys()
        .filter(|k| k.starts_with("unknown") || k.starts_with("custom-"))
        .cloned()
        .collect();

    for old_name in keys_to_fix {
        if let Some(svc) = graph.services.remove(&old_name) {
            let new_name = if let Some(port) = svc.port {
                if let Some(container) = port_to_container.get(&port) {
                    container.clone()
                } else if let Some(program) = port_to_program.get(&port) {
                    if program == "docker-proxy" {
                        format!("container-{port}")
                    } else {
                        format!("{program}-{port}")
                    }
                } else {
                    old_name.clone()
                }
            } else {
                old_name.clone()
            };
            let mut renamed = svc;
            renamed.name = new_name.clone();
            graph.services.insert(new_name, renamed);
        }
    }
}

fn extract_port_from_ss(line: &str) -> Option<u16> {
    // ss -tlnp format: "LISTEN  0  128  0.0.0.0:5432  0.0.0.0:*  users:..."
    // The local address is the 4th field (index 3)
    let parts: Vec<&str> = line.split_whitespace().collect();
    if parts.len() >= 4 {
        // Try the 4th column first (local address:port)
        if let Some(port) = parts[3].rsplit(':').next()
            .and_then(|s| s.parse::<u16>().ok())
            .filter(|&p| p > 0)
        {
            return Some(port);
        }
    }
    // Fallback: scan for address:port patterns
    for part in &parts {
        if let Some(port) = part.rsplit(':').next()
            .and_then(|s| s.parse::<u16>().ok())
            .filter(|&p| p > 0)
            .filter(|_| part.contains(':') && !part.contains("(("))
        {
            return Some(port);
        }
    }
    None
}

fn extract_program_from_ss(line: &str) -> Option<String> {
    let start = line.find("((\"")? + 3;
    let end = start + line[start..].find('"')?;
    let name = &line[start..end];
    if name.is_empty() { None } else { Some(name.to_string()) }
}

// ─── System prompts ───

const COMMAND_GEN_SYSTEM_PROMPT: &str = r#"You are a Linux systems expert. Given a server fingerprint, generate read-only discovery commands to map the complete infrastructure.

For each command, specify:
- cmd: the exact command to run (single command, NO pipes, NO semicolons, NO &&)
- purpose: what information it provides (1 sentence)
- needs_sudo: true if this typically requires root

RULES:
- ONLY read-only commands. No modifications, no writes, no restarts.
- NO shell composition (no pipes |, no ;, no &&, no $()). Each command must be atomic.
- Prefer structured output: --format json, -o json, -o wide, --no-headers
- For Docker: docker ps, docker inspect, docker network ls
- For K8s: kubectl get pods/svc/ingress/deployments -A -o wide
- For web servers: nginx -T, apache2ctl -S, haproxy config paths
- For compose: find compose files, then cat each one
- Read systemd unit files for running services
- Max 30 commands, prioritized by information value

Return ONLY a JSON array: [{"cmd": "...", "purpose": "...", "needs_sudo": false}]"#;

const EXTRACTION_SYSTEM_PROMPT: &str = r#"You receive raw system output from a Linux server. Extract all running services.

SERVICE IDENTIFICATION:
1. From ss output: read the "users:" field for program names (e.g., users:(("nginx",pid=1234,...)))
2. Cross-reference PIDs with ps output for full command lines
3. Docker containers: use the container name from docker ps/inspect, NOT "docker-proxy"
4. K8s pods: use the pod name and namespace
5. Systemd services: use the unit name
6. NEVER use "unknown" — use the actual program/container/pod name

NAMING: real names only. Multiple instances → append port (postgres-5432, postgres-5433).

TYPES: Web (HTTP/API), Database (postgres/mysql/mongo), Cache (redis/memcached), Queue (rabbitmq/kafka), LoadBalancer (nginx proxy/haproxy), Custom (other)

DEPENDENCIES: only include those clearly evidenced:
- proxy_pass/upstream in web server config → dependency
- DATABASE_URL/REDIS_URL in env vars → dependency
- K8s service references → dependency

Return ONLY valid JSON. Be conservative with dependencies."#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_port_from_ss_line() {
        let line = "LISTEN 0 128 0.0.0.0:5432 0.0.0.0:* users:((\"postgres\",pid=1234,fd=5))";
        assert_eq!(extract_port_from_ss(line), Some(5432));
    }

    #[test]
    fn extract_program_from_ss_line() {
        let line = "LISTEN 0 128 0.0.0.0:5432 0.0.0.0:* users:((\"postgres\",pid=1234,fd=5))";
        assert_eq!(extract_program_from_ss(line), Some("postgres".into()));
    }

    #[test]
    fn fingerprint_serialization() {
        let fp = ServerFingerprint {
            os: "Ubuntu 22.04".into(),
            arch: "x86_64".into(),
            init_system: "systemd".into(),
            runtimes: vec!["docker".into()],
            orchestrators: vec![],
            web_servers: vec!["nginx".into()],
            listening_ports: vec![(80, "nginx".into()), (5432, "postgres".into())],
        };
        let json = serde_json::to_string(&fp).unwrap();
        assert!(json.contains("Ubuntu"));
        assert!(json.contains("docker"));
    }

    #[test]
    fn command_result_classification() {
        let success = CommandResult::Success { cmd: "ls".into(), output: "file".into() };
        assert!(!success.is_permission_denied());

        let denied = CommandResult::PermissionDenied { cmd: "cat /etc/shadow".into(), error: "Permission denied".into() };
        assert!(denied.is_permission_denied());
        assert_eq!(denied.cmd(), "cat /etc/shadow");
    }

    #[test]
    fn discovery_command_deserialization() {
        let json = r#"[{"cmd": "docker ps", "purpose": "list containers", "needs_sudo": false}]"#;
        let cmds: Vec<DiscoveryCommand> = serde_json::from_str(json).unwrap();
        assert_eq!(cmds.len(), 1);
        assert_eq!(cmds[0].cmd, "docker ps");
        assert!(!cmds[0].needs_sudo);
    }
}
